Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,17 +26,13 @@ jobs:
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
+          $releases = gh release list -L 1 --json name -q '.[].name' || true
           $ourLatestRelease = ""
-          try {
-            $releases = gh release list -L 1 --json name -q '.[].name'
-            if ($releases) {
-              $ourLatestRelease = $releases[0]
-              echo "Our latest release: $ourLatestRelease"
-            } else {
-              echo "No releases found. Setting OUR_LATEST_RELEASE to empty string."
-            }
-          } catch {
-            echo "Error fetching releases. Setting OUR_LATEST_RELEASE to empty string."
+          if ($releases) {
+            $ourLatestRelease = $releases[0]
+            echo "Our latest release: $ourLatestRelease"
+          } else {
+            echo "No releases found or error occurred. Setting OUR_LATEST_RELEASE to empty string."
           }
           echo "OUR_LATEST_RELEASE=$ourLatestRelease" >> $env:GITHUB_ENV
 
